name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"branch":"main"}' \
            https://api.render.com/v1/services/d04l0lqli9vc73espm2g/deploys

      - name: Run migrations on Render
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.RENDER_SSH_PRIVATE_KEY }} user@<your_render_host> "cd /path/to/your/project && python manage.py migrate --noinput"